### ISSUE TITLE
MICROVIZ builder doesn't work

### ISSUE THREAD

**Issue by bettinardi** [tlumip/tlumip#109]
Here's the error record from that latest run - note that it has never been successfully run, I believe is the first time we have had enough RAM to get to this error message:

8-Mar-2019 15:14, INFO, Finished building individual year micro viz db for D:\swim2\SWIMR_Test\outputs\t48
28-Mar-2019 15:14, INFO, [Previously saved workspace restored]
28-Mar-2019 15:14, INFO, 
28-Mar-2019 15:14, INFO, Loading required package: DBI
28-Mar-2019 15:17, INFO, Error in `$<-.data.frame`(`*tmp*`, "LD_HOUSEHOLD_PATTERN", value = c("AWAY",  : 
28-Mar-2019 15:17, INFO,   replacement has 3127946 rows, data has 3143442
28-Mar-2019 15:17, INFO, Calls: $<- -> $<-.data.frame
28-Mar-2019 15:17, INFO, Execution halted
28-Mar-2019 15:17, ERROR, Errors occurred building viz db.
28-Mar-2019 15:17, INFO, Finished building individual year micro viz db for D:\swim2\SWIMR_Test\outputs\t32
28-Mar-2019 15:17, INFO, Error in `$<-.data.frame`(`*tmp*`, "LD_HOUSEHOLD_PATTERN", value = c("AWAY",  : 
28-Mar-2019 15:17, INFO,   replacement has 3197761 rows, data has 3213319
28-Mar-2019 15:17, INFO, Calls: $<- -> $<-.data.frame
28-Mar-2019 15:17, INFO, Execution halted
28-Mar-2019 15:17, ERROR, Errors occurred building viz db.
28-Mar-2019 15:17, INFO, Finished building individual year micro viz db for D:\swim2\SWIMR_Test\outputs\t35
28-Mar-2019 15:17, INFO, Error in `$<-.data.frame`(`*tmp*`, "LD_HOUSEHOLD_PATTERN", value = c("AWAY",  : 
28-Mar-2019 15:17, INFO,   replacement has 3242311 rows, data has 3258714
28-Mar-2019 15:17, INFO, Calls: $<- -> $<-.data.frame
28-Mar-2019 15:17, INFO, Execution halted
28-Mar-2019 15:17, ERROR, Errors occurred building viz db.
28-Mar-2019 15:17, INFO, Finished building individual year micro viz db for D:\swim2\SWIMR_Test\outputs\t38
28-Mar-2019 15:17, INFO, Error in `$<-.data.frame`(`*tmp*`, "LD_HOUSEHOLD_PATTERN", value = c("AWAY",  : 
28-Mar-2019 15:17, INFO,   replacement has 2678132 rows, data has 2692376
28-Mar-2019 15:17, INFO, Calls: $<- -> $<-.data.frame
28-Mar-2019 15:17, INFO, Execution halted
28-Mar-2019 15:17, ERROR, Errors occurred building viz db.
28-Mar-2019 15:17, INFO, Finished building individual year micro viz db for D:\swim2\SWIMR_Test\outputs\t23
28-Mar-2019 15:17, INFO, Error in `$<-.data.frame`(`*tmp*`, "LD_HOUSEHOLD_PATTERN", value = c("AWAY",  : 
28-Mar-2019 15:17, INFO,   replacement has 3298361 rows, data has 3314952
28-Mar-2019 15:17, INFO, Calls: $<- -> $<-.data.frame
28-Mar-2019 15:17, INFO, Execution halted
28-Mar-2019 15:17, INFO, Error in `$<-.data.frame`(`*tmp*`, "LD_HOUSEHOLD_PATTERN", value = c("AWAY",  : 
28-Mar-2019 15:17, INFO,   replacement has 2889557 rows, data has 2903408
28-Mar-2019 15:17, INFO, Calls: $<- -> $<-.data.frame
28-Mar-2019 15:17, INFO, Execution halted
28-Mar-2019 15:17, ERROR, Errors occurred building viz db.
28-Mar-2019 15:17, INFO, Finished building individual year micro viz db for D:\swim2\SWIMR_Test\outputs\t26
28-Mar-2019 15:17, ERROR, Errors occurred building viz db.
28-Mar-2019 15:17, INFO, Finished building individual year micro viz db for D:\swim2\SWIMR_Test\outputs\t41
28-Mar-2019 15:17, INFO, Error in `$<-.data.frame`(`*tmp*`, "LD_HOUSEHOLD_PATTERN", value = c("AWAY",  : 
28-Mar-2019 15:17, INFO,   replacement has 3352235 rows, data has 3369687
28-Mar-2019 15:17, INFO, Calls: $<- -> $<-.data.frame
28-Mar-2019 15:17, INFO, Execution halted
28-Mar-2019 15:17, INFO, Error in `$<-.data.frame`(`*tmp*`, "LD_HOUSEHOLD_PATTERN", value = c("AWAY",  : 
28-Mar-2019 15:17, INFO,   replacement has 3408331 rows, data has 3425156
28-Mar-2019 15:17, INFO, Calls: $<- -> $<-.data.frame
28-Mar-2019 15:17, INFO, Execution halted
28-Mar-2019 15:17, ERROR, Errors occurred building viz db.
28-Mar-2019 15:17, INFO, Finished building individual year micro viz db for D:\swim2\SWIMR_Test\outputs\t44
28-Mar-2019 15:17, ERROR, Errors occurred building viz db.
28-Mar-2019 15:17, INFO, Finished building individual year micro viz db for D:\swim2\SWIMR_Test\outputs\t47
28-Mar-2019 15:17, INFO, Error in `$<-.data.frame`(`*tmp*`, "LD_HOUSEHOLD_PATTERN", value = c("AWAY",  : 
28-Mar-2019 15:17, INFO,   replacement has 3044214 rows, data has 3058857
28-Mar-2019 15:17, INFO, Calls: $<- -> $<-.data.frame
28-Mar-2019 15:17, INFO, Execution halted
28-Mar-2019 15:17, ERROR, Errors occurred building viz db.
28-Mar-2019 15:17, INFO, Finished building individual year micro viz db for D:\swim2\SWIMR_Test\outputs\t29
28-Mar-2019 15:17, INFO, Error in `$<-.data.frame`(`*tmp*`, "LD_HOUSEHOLD_PATTERN", value = c("AWAY",  : 
28-Mar-2019 15:17, INFO,   replacement has 2546071 rows, data has 2559193
28-Mar-2019 15:17, INFO, Calls: $<- -> $<-.data.frame
28-Mar-2019 15:17, INFO, Execution halted
28-Mar-2019 15:17, ERROR, Errors occurred building viz db.
28-Mar-2019 15:17, INFO, Finished building individual year micro viz db for D:\swim2\SWIMR_Test\outputs\t20
28-Mar-2019 15:17, INFO, Error in `$<-.data.frame`(`*tmp*`, "LD_HOUSEHOLD_PATTERN", value = c("AWAY",  : 
28-Mar-2019 15:17, INFO,   replacement has 3466443 rows, data has 3483730
28-Mar-2019 15:17, INFO, Calls: $<- -> $<-.data.frame
28-Mar-2019 15:17, INFO, Execution halted
28-Mar-2019 15:17, ERROR, Errors occurred building viz db.
28-Mar-2019 15:17, INFO, Finished building individual year micro viz db for D:\swim2\SWIMR_Test\outputs\t50
28-Mar-2019 15:17, ERROR, micro viz db builder had errors
Exception in thread "main" java.lang.IllegalStateException: micro viz db builder had errors
	at com.pb.tlumip.ao.VizDbBuilder.buildVizDb(VizDbBuilder.java:115)
	at com.pb.tlumip.ao.VizDbBuilder.buildMicroVizDb(VizDbBuilder.java:99)
	at com.pb.tlumip.ao.ModelEntry.runMicroViz(ModelEntry.java:271)
	at com.pb.tlumip.ao.ModelEntry.main(ModelEntry.java:339)
SUCCESS: The process "java.exe" with PID 5440 has been terminated.
ERROR: The process "Rterm.exe" not found.
ERROR: The process "R.exe" not found.
ERROR: The process "python.exe" not found.
ERROR: The process "Visum*" not found.

**Comment by bettinardi** [comment]
A better solution (as opposed to working to fix this) might be to update the wiki and just say that it doesn’t work and has been moth balled.
