### ISSUE TITLE
Migrate to Visum 20

### ISSUE THREAD

**Issue by bettinardi** [tlumip/tlumip#123]
ODOT is installing Visum 20 and will conduct tests to determine if Visum 20 creates API connection issues with the SWIM, and assuming those can be resolved, if Visum 20 greatly changes / impacts model results.

**Comment by bettinardi** [comment]
Some issue with pulling counts exists, need to investigate further:

26-Nov-2019 12:55, INFO, load csv file: D:/swim2/Ref25_0_02_V20/inputs/parameters/linkFieldNames.csv
26-Nov-2019 12:55, INFO, Create Viz output file:AllLinks.csv
26-Nov-2019 12:55, INFO, save csv file: AllLinks.csv
26-Nov-2019 12:55, INFO, Create SWIM count locations for Viz
26-Nov-2019 12:55, INFO, Traceback (most recent call last):
26-Nov-2019 12:55, INFO,   File "D:/swim2/Ref25_0_02_V20/model/code/visum/SWIM_VISUM_Main.py", line 1713, in <module>
26-Nov-2019 12:55, INFO,     s.createVizOutput()
26-Nov-2019 12:55, INFO,   File "D:/swim2/Ref25_0_02_V20/model/code/visum/SWIM_VISUM_Main.py", line 676, in createVizOutput
26-Nov-2019 12:55, INFO,     data.append(VisumHelpers.GetMulti(self.Visum.Net.CountLocations, aField))
26-Nov-2019 12:55, INFO,   File "D:\swim2\model\lib\Python27\lib\site-packages\VisumPy\helpers.py", line 50, in GetMulti
26-Nov-2019 12:55, INFO,     raw = container.GetMultiAttValues(attribute)
26-Nov-2019 12:55, INFO,   File "<COMObject <unknown>>", line 3, in GetMultiAttValues
26-Nov-2019 12:55, INFO,   File "D:\swim2\model\lib\Python27\lib\site-packages\win32com\client\dynamic.py", line 282, in _ApplyTypes_
26-Nov-2019 12:55, INFO,     result = self._oleobj_.InvokeTypes(*(dispid, LCID, wFlags, retType, argTypes) + args)
26-Nov-2019 12:55, INFO, pywintypes.com_error: (-2147352567, 'Exception occurred.', (0, u'Visum.Visum.2001', u'CComBaseContainer::GetMultiAttValues failed - module not active', None, 0, -2147352567), None)
26-Nov-2019 12:55, ERROR, Errors occurred running run TRANSIT_ASSIGNMENT
Exception in thread "main" java.lang.RuntimeException: Errors occured running run TRANSIT_ASSIGNMENT. Check log files.
